# Arithmétique
Depuis toujours l'Homme a voulu dénombrer, ajouter, soustraire et multiplier. L'étude des entiers et de leurs interactions est l'objectif de l'arithmétique.

**Objectives**  
* Utiliser efficacement la division euclidienne pour prouver des propriétes
* Introduire la notion de congruence
* Percevoir l'importance des nombres premiers et étudier une application lié à la sécurité informatique

## Divisibilité et congruence

### Divisibilité dans $\mathbb{Z}$
Soient $a$ et $b$ deux entiers relatifs tels que $b \neq 0$.  
$b$ **divise** $a$ ce qui est noté $b|a$ s'il existe un entier relatif $k$ tel que $a=kb$.

Dans ce cas on peut dire que:
* $b$ est un **diviseur** de $a$
* $a$ est un **multiple** de $b$

En Python il y a deux  opérateurs de division: la division entière `//`

In [1]:
11//2

5

et la division rationelle `/`  

In [2]:
11/2

5.5

L'opérateur modulo `%` donne le reste de la division entière.

In [3]:
11%5

1

Nous pouvons définir la fonction `divides` à l'aide de `%`

In [4]:
def divides(b, a):
    return a%b == 0

Voici trois cas concrets: $5|35, \quad 5|11, \quad 11|132$

In [5]:
divides(5, 35), divides(5, 11), divides(11, 132)

(True, False, True)

**Propriété**  
Les quatre notations sont equivalents: 
$$ b|a, \quad (-b)|a, \quad b|(-a), \quad (-b)|(-a) $$

In [6]:
divides(5, -35), divides(-5, 11), divides(-11, -132)

(True, False, True)

**Propriété**  
Si $a$ divise $b$ et si $b$ divise $c$ alors $a$ divise $c$.
$$ a|b \land b|c \implies a|c $$

Voici un example:

In [7]:
a = 11
b = 132
c = 2640
divides(a, b), divides(b, c), divides(a, c)

(True, True, True)

**Propriété**  
Si $a$ divise $b$ et si $b$ divise $a$ alors $a$ et $b$ sont égaux ou opposés
$$ a|b \land b|a \implies a=b, \quad a=-b $$

In [8]:
a = 132
b = -132
divides(a, b), divides(b, a)

(True, True)

**Propriété**  
Si $c$ divise $a$ et $b$ alors quels que soient les entiers relatifs $u$ et $v$, $c$ divise $au + bv$.  
En particulier $c$ divise $a+b$ et $a-b$

In [9]:
c = 3
b = 6
a = 9
divides(c, a+b), divides(c, a-b)

(True, True)

La relation binaire `divides` peut être représenté visuellement avec un diagramme carthésien.

In [10]:
def diagram(R, E):
    print('  ', end=' ')
    for a in E:
        print(a, end=' ')
    for a in E:
        print('\n', a, end=' ')
        for b in E:
            print('x' if R(a, b) else ' ', end=' ')

In [11]:
E = {1, 2, 3, 4, 5, 6, 7, 8}
diagram(divides, E)

   1 2 3 4 5 6 7 8 
 1 x x x x x x x x 
 2   x   x   x   x 
 3     x     x     
 4       x       x 
 5         x       
 6           x     
 7             x   
 8               x 

Cette relation est réflexive. $a|a$ est vrai. Visuellement on vérifie que tout les élement de la diagonale sont cochés.

In [12]:
all(divides(a, a) for a in E)

True

### Division euclidienne
**Théorème**  
Soit $a$ un entier naturel et $b$ un entier naturel non nul. Il existe un unique couple d'entiers naturels $(q, r)$ tel que 

$$a = bq + r \quad 0 \le r \lt b $$.

L'égalite $a = bq + r$ s'appelle la **division euclidienne** de $a$ par $b$, $q$ étant le **quotient** et $r$ le **reste**.  
On appelle $a$ le **dividende** et $b$ le **diviseur**.

La fonction `div(a, b)` retourne $(q, r)$.

In [13]:
def div(a, b):
    q = a // b
    r = a % b
    if r < 0:
        r += abs(b)
        q += 1
    return (q, r)

In [14]:
div(123, 5)

(24, 3)

Le reste $r$ est toujours positive.

In [15]:
div(-13, 5)

(-3, 2)

In [16]:
div(13, -5)

(-2, 3)

In [17]:
div(-13, -5)

(3, 2)

### Congruence dans $\mathbb{Z}$
Contrairement aux relations auxquelles nous sommes habitués, la relation de congruence ne compare pas directement deux nombres mais leur reste dans la division euclidienne par un même entier positif.

**Définition**  
Soit $n$ un entier non nul. Deux entiers relatifs $a$ et $b$ sont dits **congrus modulo n** si $(a-b)$ est divisible par $n$.  
On dit aussi que $a$ est congru à $b$ modulo $n$ et on note 

$$ a \equiv b \pmod n $$

In [18]:
def congruent(a, b, n):
    return (a-b)%n == 0

In [19]:
congruent(13, 3, 5), congruent(13, 23, 5), congruent(13, -17, 5)

(True, True, True)

La relation de congruence présente les trois propriétés suivantes:

**Propriété**  
$a \equiv b \pmod n$ si et seulement si $a$ et $b$ on le même reste dans la division euclidienne par $n$.  
Conséquences:
* $a \equiv 0 \pmod n$ si et seulement si $a$ est divisible par $n$ (donc $a|n$)
* si $a \equiv b \pmod n$ et si $b \equiv c \pmod n$ alors $a \equiv c \pmod n$

**Propriété**  
Si $k$ est un entier naturel et si $a \equiv b \pmod n$ alors:
* $a + k \equiv b + k \pmod n$
* $a - k \equiv b - k \pmod n$
* $ka \equiv kb \pmod n$
* $a^k \equiv b^k \pmod n$

Exemples:

In [20]:
a = 13
b = 3
congruent(a, b, 5), congruent(a**2001, b**2001, 5), congruent(13**2001, 3, 5)

(True, True, True)

**Propriété**  
Si $a \equiv b \pmod n$ et $c \equiv d \pmod n$ alors:
* $(a+c) \equiv (b+d) \pmod n$
* $ac \equiv bd \pmod n$



In [21]:
a, b = 17, 1
c, d = 126, 2
congruent(a, b, 4), congruent(c, d, 4)

(True, True)

Therefore:

In [22]:
congruent(a + c, b + c, 4), congruent(a*c, b*d, 4)

(True, True)

## PGCD, PPCM et applications

### Plus grand commun diviseur
Soient $a$ et $b$ deux entiers naturels non nuls.  
$D(a, b)$ est l'ensemble des commun diviseurs positifs de $a$ et $b$.  
$M(a, b)$ est l'ensemble des commun multiples positifs de $a$ et $b$.

Nous définissons l'ensemble des diviseurs de $n$

In [23]:
def divisors(n):
    return {i for i in range(1, n+1) if n%i == 0}

Par exemple:

In [24]:
divisors(12)

{1, 2, 3, 4, 6, 12}

In [25]:
divisors(28)

{1, 2, 4, 7, 14, 28}

L'ensemble des diviseurs communs est l'intersection des deux ensembles.

In [26]:
divisors(12) & (divisors(28))

{1, 2, 4}

In [27]:
def D(a, b):
    return divisors(a) & divisors(b)

In [28]:
D(12, 28)

{1, 2, 4}

Le **plus grand commun diviseur** de $a$ et $b$ qui est noté $PGCD(a, b)$ est le plus grand des éléments de $D(a, b)$.

In [29]:
def PGCD(a, b):
    return max(D(a, b))

In [30]:
PGCD(12, 28)

4

L'existence du PGCD tient au fait que $D(a, b)$ est un ensemble d'entiers non vide (il contient 1) majoré (par exemple $a$). Celle du PPCM tient au fait que $M(a, b)$ est un ensemble d'entiers non vide contenant par exemple $a \times b$ minoré par 0.

Remarques:
* $1 \in D(a, b)$
* $D(a, b) = D(a) \cap D(b)$ où $D(a)$ et $D(b)$ sont respectivement les ensembles des diviseurs positifs de $a$ et $b$.
* $b$ divise $a$ est équivalent à $D(a, b) = D(b)$ est équivlent à $PGCD(a, b) = b$

### Plus petit commun multiple
Le **plus petit commun multiple** de $a$ et $b$ qui est noté $PPCM(a, b)$ est le plus petit des éléments de $M(a, b)$.

Le nombre de multiples d'un nombre étant illimité, calculons seulement les multiples de $a$ jusqu'au produit $ab$.

In [31]:
def multiples(a, b):
    return set(range(a, a*b+1, a))

In [32]:
multiples(12, 15)

{12, 24, 36, 48, 60, 72, 84, 96, 108, 120, 132, 144, 156, 168, 180}

In [33]:
multiples(15, 12)

{15, 30, 45, 60, 75, 90, 105, 120, 135, 150, 165, 180}

Les multiples commun sont l'intersection de ces deux ensembles.

In [34]:
def M(a, b):
    return multiples(a, b) & multiples(b, a)

In [35]:
M(12, 15)

{60, 120, 180}

Le minimum de $M(a, b)$ est

In [36]:
def PPCM(a, b):
    return min(M(a, b))

In [37]:
PPCM(12, 15)

60

Une autre façon de calculer le $PPCM$ est:
$$ PPCM(a, b) = \frac {ab}{PGCD(a, b)} $$

### Algorithme d'Euclide

L'algorithme d'Euclide constitute une méthode pratique pour calculer le $PGCD$ de deux nombres. Cet algorithme repose sur la propriété suivante

Soient $a$ et $b$ deux entiers naturels non nuls tels que la division euclidienne de $a$ par $b$ s'écrive $a = bq + r$.
Alors 

$$ D(a, b) = D(b, r) $$ 

et donc 
$$PGCD(a, b) = PGCD(b, r)$$

**Méthode**  
L'algorithme d'Euclide consiste à effectuer plusieurs divisions euclidiennes successives pour transformer $D(a, b)$ en $D(r_n, 0)$ c'est-à-dire en $D(r_n)$ où $r_n$ est le dernier reste non nul des divisions euclidiennes succésives.

In [38]:
def PGCD(a, b):
    if b==0:
        return a
    else:
        return PGCD(b, a%b)

In [39]:
PGCD(12, 28), PGCD(60, 42)

(4, 6)

**Exemple**  
PGCD(60, 42) = PGCD(42, 18) = PGCD(18, 6) = PGCD(6, 0) = 6

Nous utilisons la relation suivante pour calculer $PPCM(a, b)$
$$ PPCM(a, b) = \frac{ab}{PGCD(a, b)}$$

In [40]:
def PPCM(a, b):
    return a*b // PGCD(a, b)

In [41]:
PPCM(12, 28)

84

**Propriété**  
Soient $a$, $b$ et $k$ trois entiers naturels non nuls.  
* $D(a, b) = D(PGCD(a, b))$.  
* Si $k$ divise $a$ et $b$ alors $k$ divise $PGCD(a, b)$  
* $PGCD(ka, kb) = k PGCD(a, b)$

### Nombres premiers entre eux

**Définition**  
On dit que deux entiers naturels non nuls sont **premiers entre eux**, si leur PGCD vaut 1.

Par exemple 14 et 15 sont premier entre eux.

In [42]:
PGCD(14, 15)

1

**Propriété**  
Si $PGCD(a, b) = d$ alors $\frac{a}{d}$ et $\frac b d$ sont premiers entre eux. 

### Théorème de Bézout
Soient $a$ et $b$ deux entiers naturels non nuls.  
$a$ et $b$ sont premiers entre eux si et seulement si il existe deux entiers relatifs $u$ et $v$ tels que $au + bv = 1$

Les deux nombres suivants sont premiers entre eux.

In [43]:
PGCD(66, 35)

1

Essayons de trouver $u$ et $v$ qui satisfassent $au + bv = 1$

### Théorème des restes chinois
Historiquement, ce théorème apparait dans un livre du mathématicien Sun Zi datant du 3e siècle sous la forme d'une résolution du problème suivant: *Soient des objets dont on ignore le nombre. En les comptant 3 par 3 il en reste 2; en les comptants 5 par 5, il en reste 3 et en les comptant 7 par 7 il en reste 2. Combien y a-t-il des objets?*

$x \equiv 2 \pmod 3$  
$x \equiv 3 \pmod 5$  
$x \equiv 2 \pmod 7$  



Nous pouvons établir les sets des multiples possible pour chaque condition. Par exemple les nombres modulo 3, donnant un reste de 2

In [44]:
set(range(2, 50, 3))

{2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47}

In [45]:
n = 1000
A = set(range(2, n, 3))
B = set(range(3, n, 5))
C = set(range(2, n, 7))

A & B & C

{23, 128, 233, 338, 443, 548, 653, 758, 863, 968}

Une banded de 17 pirates s'est emparée d'un butin composé de pièces d'or d'égale valeur. Ils décident de se les partager équitablement et de donner le reste au cuisinier chinois. Celui-ci recevrait 3 pièces. Mais les pirates se querellent et 6 d'entre eux sont tués. Le cuisiner recevrait alors 4 pièces. Survient alors un naufrage et seuls 6 pirates, le cuisiner et le trésor sont sauvés. Le partage laisserait 5 pièces d'or à ce dernier. Quelle est la fortune minimale que peut espérer ce dernier s'il décide d'empoisonner le reste des pirates ?

$x \equiv 3 \pmod {17} $  
$x \equiv 4 \pmod {11} $  
$x \equiv 5 \pmod {6} $  


In [46]:
n = 1000
A = set(range(3, n, 17))
B = set(range(4, n, 11))
C = set(range(5, n, 6))

A & B & C

{785}

## Les nombres premiers

### L'ensemble des nombres premières

**Définition**  
Un entier naturel $p$ est dit **premier** s'il admet exactement deux diviseurs positifs distincts: 1 et lui-même.

Par exemple 19 est premier, mais 91 n'est pas premier.

In [47]:
divisors(19), divisors(91)

({1, 19}, {1, 7, 13, 91})

Ceci permet de définir la fonction `prime(n)` qui retourne si un nombre est premier.

In [48]:
def prime(n):
    return len(divisors(n)) == 2

In [49]:
prime(13), prime(14)

(True, False)

Voici donc les nombres premiers jusqu'à 50.

In [50]:
P = [i for i in range(50) if prime(i)]
print(P)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]


**Théorème**  
Tout entier naturel $n$ non premier admet un diviseur premier $p$ tel que $2 \le p \le \sqrt n$

### Décomposition en produit de facteurs premiers

**Théorème**  
Tout entier naturel $n$ supérieur ou égal à 2 peut s'écrire sous la forme 

$$ n = p^{\alpha_1}_1 \times p^{\alpha_2}_2 \times ... \times p^{\alpha_k}_k $$ 

ou les $p_i$ sont des nombres premiers et 
les $\alpha_1$ sont des entiers naturels non nuls. Cette écriture s'appele la **décomposition en produit de facteurs premiers** de $n$. Elle est unique à l'ordre des facteurs près.

In [51]:
def factors(n):
    L = []
    p = 2
    while n > 1:
        if n % p == 0:
            L.append(p)
            n = n // p
        else:
            p = p + 1
            while not prime(p):
                p = p + 1
    return L

In [52]:
factors(120), factors(140)

([2, 2, 2, 3, 5], [2, 2, 5, 7])

Le PGCD est le nombre qui s'obtient en multipliant tous les nombres premiers apparaissant simultanément dans les deux décompositions.

In [53]:
PGCD(120, 140), 2 * 2 * 5

(20, 20)

Le PPCM est le nombre qui s'obtient en multipliant tous les nombres premiers apparaissant dans au moins une des deux décompositions.

In [54]:
PPCM(120, 140), 2 * 2 * 2 * 3 * 5 * 7

(840, 840)

### Congruence et nombres premiers

**Théorème dit petit théorème de Fermat (admis)**  
Si $p$ est un nombre premier ne divisant pas $n$ alors 
$$ n^{p-1} \equiv 1 \pmod {p} $$

Exemple

In [55]:
p = 13
n = 15
n**(p-1)

129746337890625

**Théorème**  
Si $p$ est un nombre premier et $n$ un entier alors
$$ n^p \equiv n \pmod {p} $$

### Le système de chiffrement RSA
Le chiffrement RSA est un algorithme pour crypter l'information sensible. Il a été décrit en 1977 par Rivest, Shamir et Adleman (d'ou le nom) et il repose sur l'utilisation de clés numériques créées à l'aide d'un très grand entier multiple de deux nombre premiers.

Pour comprendre le principe de ce chiffrement, partons d'un exemple concret. Une personne que nous nommons Alice veu envoyer des données sensibles en les cryptant. Elle choisit pour cela d'une part 
* $p$ et $q$ deux nombres premiers distincts et supérieur ou égaux à 3 dont le produit sera noté $n$ et d'autre part 
* un entier $e$ premier avec $(p-1)(q-1)$ et tel que $0 \lt e \lt (p-1)(q-1)$.

$(n, e)$ est la clé publique, tout le monde y a accès. En revanche $p$ et $q$ sont suffisamment grands pour que la connaissance de $n$ (qui peut avoir plusieurs centaines de chiffres) ne permette pas de les déterminer dans un temps raisonable.

Si une personne veut envoyer un message à Alice, celui-ci est numérisé puis découpé par tranches en nombres inférieurs à $n$ noté $m_1, m_2, ...$

Chacun des nombres $m_i$ est remplacé par le reste $r_i$ de la division euclidienne de $m_i^e$ par $n$ et est envoyé à Alice (et tout le monde peut éventuellement le voir). 

Alice dispose de la clé privée $(n, d)$ où 
* $d$ est l'unique entier vérifiant $1 \le d \le (p-1)(q-1)$ et 
* $ed \equiv 1 \pmod {(p-1)(q-1)}$

Alice déchiffre le message en utilisant le fait que $m_i$ est le reste de la division euclidienne de $r_i^d$ par $n$.

**Exemple**  
Alice choisit $p=3$ et $q=11$ donc $n=33$

In [56]:
p = 3
q = 11
n = p * q
(p-1) * (q-1)

20

Ensuite elle doit choisir un entier $e$ qui est premier avec $20$. Voici la liste des candidats:

In [57]:
L = [i for i in range(2, 20) if PGCD(i, 20) == 1]
L

[3, 7, 9, 11, 13, 17, 19]

Elle choisit:

In [58]:
e = 7

De la liste $L$ elle doit choisir le $d$ qui satisfait cette condition.

$ed \equiv 1 \pmod {20}$

In [59]:
[d for d in L if e*d%20 == 1]

[3]

La clé publique est $(n, e) = (33, 7)$. Supposons que Bob envoie le message $m=15$. Il est remplacé par le reste de la division euclidienne de $15^7$ par $33$, soit $27$

In [60]:
m = 15
(n, e) = (33, 7)
m ** e % n

27

Alice dispose de la clé privé $(n, d) = (33, 3)$. Elle déchiffre le message en effectuant la division euclidienne $27^3$ par $33$, le reste est 15: c'est le message de Bob. 

In [61]:
(n, d) = (33, 3)
x = 27
x ** d % n

15

Le principe du chiffrement respose sur le lemme suivant: si $x = m^e \pmod {n}$ alors $m \equiv x^d \pmod{n}$.  
Ainsi, si $m$ est le message de Bob, $x$ est le reste de la division euclidienne de $m^e$ par $n$ (le message transmis à Alice). Alice peut obtenir $m$ qui est le reste de la division euclidieenne de $x^d$ par $n$.

## Les systèmes de numération
**Définitions**  
Un **système de numération** est un ensemble de symboles appelés **chiffres** et ainsi que des règles permettant de représenter des nombres. On appelle **base** d'un système de numération le nombre de chiffres utilisé pour représenter un nombre.

* Les humains utilisent le système décimale qui est un système de numération de base 10 et qui utilise les chiffres `0123456789`.  
* Les ordinateurs utilisent le système binaire qui est un système de base 2, où les nombre s'écrivent avec seulement les chiffres `01`

### Conversion depuis une base $b$
Commençons par donner la méthode permettant d'obtenir la valeur décimale d'un nombre écrit en base $b$. Le nombre en base $b$ est donnée sous forme de chaine de caractères `s`.  Cette chaine est composé de chiffres appartenant à l'ensemble ordonné `S` Par exemple pour un système de numération hexadécimal, en base 16, on utilise d'habitude l'ensemble des chiffres:

In [62]:
S = '0123456789abcdef'

La méthode `index` permet de trouver la valeur numérique d'un chiffre. Par exemple le chiffre `f` a la valeur numérique 15.

In [63]:
S.index('f')

15

Supposons que le nombre $s$ s'écrit en base $b$ comme séquence de chiffres $s_n...s_2s_1s_0$. Sa valeur numériques est alors:

$$ s_n \times b^n + ...  + s_2 \times b^2 + s_1 \times b^1 + s_0 \times b^0 $$

Remarques: 
* le string est invérse avec `s[::-1]`
* la fonction `enumerate` fournit un tuple `(i, c)` avec l'index et un caractère de la chaine

In [64]:
def fromBase(s, base):
    S = '0123456789abcdef'
    n = 0
    for (i, c) in enumerate(s[::-1]):
        n += S.index(c) * base**i
    return n

Voici trois exemples:

In [65]:
fromBase('fff', 16), fromBase('abc', 16), fromBase('11111', 2), 

(4095, 2748, 31)

Pour la base hexadécimal, octal et binaire Python prévois une notation litérale utilisant les prefixes suivants: 
* `0x` pour hexadécimal
* `0o` pour octal
* `0b` pour binaire

Voici trois examples:

In [66]:
0xabc, 0o123, 0b01010101

(2748, 83, 85)

### Conversion vers une base $b$
Voyons maintenant la méthode perméttant d'obtenir la séquence de chiffres en base $b$ d'un nombre dont la valeur numérique est donnée.

L'algorithme utilisé s'appuye sur des divisions successives.
* le nombre en base $b$ est représenté comme chaine de caractères $s$
* l'ensemble des chiffres pour la numération en base $b$ est donné dans la chaine $S$
* Le reste de la division `i = n % base` donne le nouveau chiffre à ajouter à $s$
* le nouveau chiffre est obtenu en indexant $S$ et en l'ajoutant à gauche de la chaine $s$
* l'algorithme coninue avec `n = n // base`


In [67]:
def toBase(n, base):
    S = '0123456789abcdef'
    s = ''
    
    while n > 0:
        i = n % base
        n = n // base
        s = S[i] + s
    return s

Voici le nombre $n$ représenté dans trois bases différentes:

In [68]:
n = 12345678
toBase(n, 16), toBase(n, 3), toBase(n, 2)

('bc614e', '212020020002100', '101111000110000101001110')

### La fonction `format`
La fonction `format` permet de formater un nombre apparaissant à l'intérieur d'une chaine sous forme binaire, octale ou hexadécimale. Cette méthode de la classe `str` est utilisé avec la notation `s.format(p0, p1, ..)`. 
* Le string `s` contient des marquers `{}` ou les paramètres p sont insérés
* Le marquer `{}` contient des options de mise en format
    * `{:x}` pour le format hexadécimale (base 16)
    * `{:o}` pour le format octale (base 8)
    * `{:b}` pour le format binare (base 2)

In [69]:
n = 12345678
print('forme hexadécimale: {:x}'.format(n))
print('forme octale: {:b}'.format(n))
print('forme binaire: {:o}'.format(n))

forme hexadécimale: bc614e
forme octale: 101111000110000101001110
forme binaire: 57060516


Il est également possible de spécifier le nombre de positions et de les remplir avec des `0`.

In [70]:
n = 30
print('0x{:08x}'.format(n))
print('0b{:08b}'.format(n))

0x0000001e
0b00011110


## Exercices

### Exercice 1 - divisible par 3
Prouver que la somme de trois entiers consecutifs est toujours divisible par 3.

La somme de trois entiers consécutifs à partr de l'entier $n$ est:   
$ S = n + (n+1) + (n+2) = 3n+3 = 3(n+1)$  
Comme $n+1$ est un entier, $S$ est divisible par 3.

### Exercice 2 - division euclidienne
Ecrire les divisions euclidiennes de $a$ par $b$ dans les cas suivants:
* $a=270$ et $b=12$
* $a=-151$ et $b=9$
* $a=-200$ et $b=-3$

In [71]:
div(270, 12), div(-151, 9), div(-200, -3)

((22, 6), (-17, 2), (67, 1))

### Exercice 3 - division euclidienne
On suppose que $a$ et $a'$ sont des entiers positifs, que $b$ est un entier strictement positif et que les divisions euclidiennes de $a$ et $a'$ par $b$ sont $a = bq + r$ et $a'=bq'+r'$  
Quelle est la division euclidienne de $a + a'$ par $b$?

$a + a' = b(q+q') + (r+r')$

### Exercice 4 - reste
Donner le reste de la divison euclidienne de $13^{218}$ par 5.

$13^{218} \equiv 3^{218} \equiv 9^{109} \equiv 4^{109} \equiv 16^{54}4 \equiv 1^{54}4 \equiv 4\pmod{5} $

In [72]:
13**218 % 5

4

### Exercice 5 - PGCD et PPCM
Déterminer à l'aide de l'algorithme d'Euclide PGCD(2268, 360). En déduire PPCM(2268, 360).

In [73]:
a = 2268
b = 360

while b != 0:
    print (a, b)
    (a, b) = (b, a%b)
    
print('PGCD =', a)
print('PPCM =', 2268 * 360 // a)

2268 360
360 108
108 36
PGCD = 36
PPCM = 22680


### Exercice 6 - bouquet
Un fleuriste dispose de 270 roses, 378 lys et 126 oeillets. Il souhaite réaliser un maximum de bouquets identiqeus en utilisant toutes ses fleurs. Comment doit-il se prendre ?

In [74]:
a = 270
b = 378
c = 126
d = PGCD(PGCD(a, b), c)
print(d, 'bouquets avec')
print(a//d, 'roses,', b//d, 'lys et', c//d, 'oeillets')

18 bouquets avec
15 roses, 21 lys et 7 oeillets


### Exercice 7 - algorithme d'Euclide
A l'aide de l'algorithme d'Euclide, déterminer $u$ et $v$ tels que $20u +13v = 1$

### Exercice 8 - perles
Emma a entre 300 et 400 perles. Si elle fait des paquets de 15 perles il lui en restent 3, et si elle fait des paquets des boites de 17, il lui en reste 4. De combien de perles dispose-t-elle ?

In [75]:
A = set(range(3, 400, 15))
B = set(range(4, 400, 17))
A & B

{123, 378}

### Exercice 9 - nombre premiers
Donner la liste des nombres premiers inférieur à 150.

In [76]:
L = {i for i in range(2, 150) if len(divisors(i)) == 2}
print(L)

{2, 3, 131, 5, 7, 137, 11, 139, 13, 17, 19, 149, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127}


### Exercice 10 - nombre premier ?
Les nombres 493 et 293 sont-ils premiers ?

In [77]:
for i in (493, 293):
    if len(divisors(i)) == 2 :
        print(i, 'is prime')
    else:
        print(i, 'is not prime')

493 is not prime
293 is prime


### Exercice 11 - divisieurs
Donner la liste des diviseurs de 140.

In [78]:
divisors(140)

{1, 2, 4, 5, 7, 10, 14, 20, 28, 35, 70, 140}

### Exercice 12 - facteurs premiers
Decomposer en produit de facteurs premiers les nombres 2268 et 360, en déduire leur PGCD et leur PPCM.

In [79]:
a = 2268
b = 360
        
print(factors(a))
print(factors(b))

[2, 2, 3, 3, 3, 3, 7]
[2, 2, 2, 3, 3, 5]


In [80]:
d = 2 * 2 * 3 * 3
m = 2268 * 2 * 5
(d, m)

(36, 22680)

### Exercice 13 - RSA
Reprendre l'exemple d'étude du cryptage RSA avec les mêmes valeurs de $p$ et $q$ mais avec $e=13$.  
Détailler la transmission de $m=5$

In [81]:
p = 3
q = 11
n = p * q
e = 13
(n, e) #public key

(33, 13)

In [82]:
m = 5
x = m ** e % n 
x #encrypted message

26

In [83]:
[d for d in L if e*d%20 == 1]

[137, 17, 37, 97]

In [84]:
d = 17
(n, d) #private key

(33, 17)

In [85]:
x ** d % n

5

### Exercice 14 - base 10
Ecrire en base 10 le nombre $3142_5$.

In [86]:
fromBase('3141', 5)

421

### Exercice 15 - base 7
Ecrire en base 7 le nombre $2102_3$.

In [87]:
n = fromBase('2102', 3)
toBase(n, 7)

'122'